<?php
class classes_orderItem extends core_DBObject {
    public $order_id = null; //Заказ
    public $item_id = null; //номер в заказе
    public $code_stat = null; //код для статистики
    public $add_date = null; //дата добавления
    public $dates_rdy = null; //дата готовности
    public $status_item = null; //текущий статус заявки
    public $name_item = null; //наименование
    public $size = null; //размер
    public $total = null; //кол-во
    public $units = null; //ед измерения
    public $price = null; //цена
    public $summ_sys = null; //просчет системы
    public $summ = null; //сумма
    public $view_diz = null; //список кодов дизайна
    public $view_press = null; //есть ли препресс
    public $fast = null; //Срочность
    public $template = null; //исходная форма
    public $template_calc = null; //полный расчет
    public $press_diz = null; //папка для файлов печати
    public $print_diz = null; //папка для файлов препресса
    public $cl_file = null; //файлы клиента
    public $comment = null; //комментарий

    public function __construct()
    {
        parent::__construct('order_items', 'ID', 'classes_orderItem');
    }

    public function viewById($id)
    {
        parent::loadById($id); // TODO: Change the autogenerated stub
        if(API::isJSON($this->template_calc)) {
            $this->template_calc = json_decode($this->template_calc);
            if(isset($this->template_calc->data)) {
                foreach ($this->template_calc->data as $k => $v) {
                    $list_mat = factorys_classes::getObject('classes_klMat')->selectByQuery('SELECT `kl_mat`.* FROM `kl_mat` WHERE `kl_mat`.`id` = ' . $v->p_mat);
                    $v->p_mat = $list_mat[0]->title;
                }
            }
        }
        $name = factorys_classes::getObject('core_Entity')
            ->select("SELECT `directory_status_item`.`name` FROM `directory_status_item` WHERE `directory_status_item`.`ID` = '" . $this->status_item . "'")[0]['name'];
        $icon = factorys_classes::getObject('core_Entity')
            ->select("SELECT `directory_status_item`.`icon` FROM `directory_status_item` WHERE `directory_status_item`.`ID` = '" . $this->status_item . "'")[0]['icon'];
        $this->status_item = '<span class="' . $icon . '">' . $name . '</span>';

        $this->add_date = API::FormatDate($this->add_date, CONSTANTS::REPORT_DATETIME_FORMAT);
        $this->dates_rdy = API::FormatDate($this->dates_rdy, CONSTANTS::REPORT_DATETIME_FORMAT);

        $this->fields = [
            'p_namepart' => API::__('p_namepart'),
            'p_mat' => API::__('p_mat'),
            'Layout' => API::__('Layout'),
        ];
    }

    /*
     * Переход от расчета к заявке
     */
    public function convertCalcToItem(classes_Bitrix24TemplateCalculation $bitrix, $order_id) {
        $msg = null;

        do {
            if(empty($bitrix) || !$bitrix->getInit()) {
                $msg = 'Не задан объект расчета';
                break;
            }
            $order = new classes_orders();
            if(null !== ($msg = $order->loadById($order_id)))
                break;

            $form = json_decode($bitrix->data, true);
            $form_calc = json_decode($bitrix->data_calc);

            $this->order_id = $order->getId();
            if(null !== ($msg = $this->getLasItem()))
                break;
            $this->size = $form['p_size'];
            $this->total = $form['p_cir'];
            if(null !== ($msg = $this->getUnit($form['unit_prod1'])))
                break;
            $this->price = !empty($form_calc->result->summ_one_product_hand) ? $form_calc->result->summ_one_product_hand : $form_calc->result->summ_one_product;
            $this->summ_sys = $form_calc->result->all_summ_order_byn;
            $this->summ = !empty($form_calc->result->all_summ_order_calc_hand) ? $form_calc->result->all_summ_order_calc_hand : $form_calc->result->all_summ_order_byn_calc;
            $this->view_diz = $form_calc->result->design_id;
            $this->view_press = (!empty($form['p_press_']) && !empty($form['ViewPressCheck'])) ? 1 : 0;
            $this->fast = $form['p_fast'];
            $this->template = $bitrix->data;
            $this->template_calc = $bitrix->data_calc;
            $this->comment = $form['list_comm'];

            /** пути к файлам */
            $path = "files/prod/" . $this->order_id . "/" . $this->item_id . "/";
            $this->press_diz = $path . "press";
            if (null !== ($msg = API::createPath($this->press_diz)))
                break;
            $this->print_diz = $path . "diz";
            if (null !== ($msg = API::createPath($this->print_diz)))
                break;
            $this->cl_file = $path . "client";
            if (null !== ($msg = API::createPath($this->cl_file)))
                break;

            /** статус заявки */
            if(!empty($form['ViewDesignCheck'])) {
                $this->status_item = CONSTANTS::STATUS10;
            } else if(!empty($form['ViewPressCheck'])) {
                $this->status_item = CONSTANTS::STATUS11;
            } else {
                $this->status_item = CONSTANTS::STATUS1;
            }

        } while(false);

        return $msg;
    }

    /*
     * Определяем последнюю позицию
     */
    protected function getLasItem() {
        $msg = null;

        do {
            if(empty($this->order_id)) {
                $msg = 'Не задан номер заказа';
                break;
            }

            $list = $this->select('SELECT IFNULL(MAX(order_items.item_id) + 1, 1) as item_id FROM order_items WHERE order_items.ORDER_ID=' . intval($this->order_id));
            $this->item_id = intval($list[0]['item_id']);

        } while(false);

        return $msg;
    }

    /*
     * Возвращает единицу измерения
     */
    protected function getUnit($value = null) {
        $msg = null;

        do {
            if(empty($value)) {
                $msg = 'Не задано значение для единицы измерения';
                break;
            }
            $_unit = new classes_units();
            if(ctype_digit($value)) {
                if(null !== ($msg = $_unit->loadById($value)))
                    break;
            } else {
                if(null !== ($msg = $_unit->loadByUnique('Name', $value)))
                    break;
            }
            $this->units = $_unit->getId();

        } while(false);

        return $msg;
    }
}
?>