/** ВЫГРУЖЕНО */
#Сохранение уровней доступа
INSERT INTO `accesslevel` VALUES (5, 1, 'Доступ к странице заказов' ,'ACCESS_PAGE_ORDERS');
INSERT INTO `accesslevel` VALUES (6, 1, 'Доступ к странице клиентов' ,'ACCESS_PAGE_CLIENTS');
INSERT INTO `accesslevel` VALUES (7, 1, 'Доступ к странице ТН' ,'ACCESS_PAGE_TN');
INSERT INTO `accesslevel` VALUES (8, 1, 'Доступ к странице оплат' ,'ACCESS_PAGE_PAYMENTS');
INSERT INTO `accesslevel` VALUES (9, 1, 'Доступ к странице подготовки файлов' ,'ACCESS_PAGE_TASKS');
INSERT INTO `accesslevel` VALUES (10, 1, 'Доступ к странице склада' ,'ACCESS_PAGE_STOCK');
INSERT INTO `accesslevel` VALUES (11, 1, 'Доступ к странице загруженности производства' ,'ACCESS_PAGE_WORKLOAD');
INSERT INTO `accesslevel` VALUES (12, 1, 'Доступ к странице производства' ,'ACCESS_PAGE_WORKS');
INSERT INTO `accesslevel` VALUES (13, 1, 'Доступ к отчетам' ,'ACCESS_PAGE_REPORTS');
INSERT INTO `accesslevel` VALUES (14, 1, 'Доступ к нераспределенным контактам из фреша' ,'ACCESS_PAGE_REPORTS_CONTACTS_FRESH');
INSERT INTO `accesslevel` VALUES (15, 1, 'Доступ к отчету по артлайнерам' ,'ACCESS_PAGE_REPORTS_ARTLINER');
INSERT INTO `accesslevel` VALUES (16, 1, 'Доступ к отчету по оформленным заказам' ,'ACCESS_PAGE_REPORTS_ORDERS');
INSERT INTO `accesslevel` VALUES (17, 1, 'Доступ к отчету по дизайнерам' ,'ACCESS_PAGE_REPORTS_DESIGNS');
INSERT INTO `accesslevel` VALUES (18, 1, 'Доступ к отчету по поставщикам' ,'ACCESS_PAGE_REPORTS_PROVIDERS');
INSERT INTO `accesslevel` VALUES (19, 1, 'Доступ к отчету по клиентам с возможностью сохранения в Excel' ,'ACCESS_PAGE_REPORTS_ORDERS_TO_XLS');
INSERT INTO `accesslevel` VALUES (20, 1, 'Доступ к странице настроек' ,'ACCESS_PAGE_SETTINGS');
INSERT INTO `accesslevel` VALUES (21, 1, 'Доступ к классификатору склада' ,'ACCESS_PAGE_SETTINGS_TREE');
INSERT INTO `accesslevel` VALUES (22, 1, 'Доступ к настройке продуктов' ,'ACCESS_PAGE_SETTINGS_PRODUCTS');
INSERT INTO `accesslevel` VALUES (23, 1, 'Доступ к настройке кодов продуктов' ,'ACCESS_PAGE_SETTINGS_CODE_PRODUCTS');
INSERT INTO `accesslevel` VALUES (24, 1, 'Доступ к настройке оборудования' ,'ACCESS_PAGE_SETTINGS_EQUIPMENTS');
INSERT INTO `accesslevel` VALUES (25, 1, 'Доступ к настройке операций' ,'ACCESS_PAGE_SETTINGS_OPERATIONS');
INSERT INTO `accesslevel` VALUES (26, 1, 'Доступ к календарю' ,'ACCESS_PAGE_SETTINGS_CALENDAR');
INSERT INTO `accesslevel` VALUES (27, 1, 'Доступ к сбросу паролей пользователей' ,'ACCESS_PAGE_SETTINGS_RESET_PASSWORD');
INSERT INTO `accesslevel` VALUES (28, 1, 'Доступ к справочникам' ,'ACCESS_PAGE_DIRECTORY');
INSERT INTO `accesslevel` VALUES (29, 1, 'Доступ к справочнику пользователей' ,'ACCESS_PAGE_DIRECTORY_USERS');
INSERT INTO `accesslevel` VALUES (30, 1, 'Доступ к справочнику материалов' ,'ACCESS_PAGE_DIRECTORY_MATERIALS');
INSERT INTO `accesslevel` VALUES (31, 1, 'Доступ к справочнику штампов' ,'ACCESS_PAGE_DIRECTORY_STAMPS');
INSERT INTO `accesslevel` VALUES (32, 1, 'Доступ к справочнику параметров' ,'ACCESS_PAGE_DIRECTORY_PARAMETRS');
INSERT INTO `accesslevel` VALUES (33, 1, 'Доступ к справочнику дизайна' ,'ACCESS_PAGE_DIRECTORY_DESIGNS');
INSERT INTO `accesslevel` VALUES (34, 1, 'Доступ к справочнику единиц измерения' ,'ACCESS_PAGE_DIRECTORY_UNITS');

#Обновление меню
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_ORDERS' WHERE `accessmenu`.`ID`=1;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_CLIENTS' WHERE `accessmenu`.`ID`=3;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_REPORTS_CONTACTS_FRESH' WHERE `accessmenu`.`ID`=4;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_REPORTS_ARTLINER' WHERE `accessmenu`.`ID`=5;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_TN' WHERE `accessmenu`.`ID`=6;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_PAYMENTS' WHERE `accessmenu`.`ID`=7;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_TASKS' WHERE `accessmenu`.`ID`=8;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_STOCK' WHERE `accessmenu`.`ID`=9;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_WORKLOAD' WHERE `accessmenu`.`ID`=10;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_WORKS' WHERE `accessmenu`.`ID`=11;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_REPORTS' WHERE `accessmenu`.`ID`=12;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_REPORTS_ORDERS' WHERE `accessmenu`.`ID`=13;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_REPORTS_DESIGNS' WHERE `accessmenu`.`ID`=14;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_REPORTS_PROVIDERS' WHERE `accessmenu`.`ID`=15;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_REPORTS_ORDERS_TO_XLS' WHERE `accessmenu`.`ID`=16;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_SETTINGS' WHERE `accessmenu`.`ID`=17;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_SETTINGS_TREE' WHERE `accessmenu`.`ID`=18;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_SETTINGS_PRODUCTS' WHERE `accessmenu`.`ID`=19;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_SETTINGS_CODE_PRODUCTS' WHERE `accessmenu`.`ID`=20;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_SETTINGS_EQUIPMENTS' WHERE `accessmenu`.`ID`=21;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_SETTINGS_OPERATIONS' WHERE `accessmenu`.`ID`=22;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_SETTINGS_CALENDAR' WHERE `accessmenu`.`ID`=23;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_SETTINGS_RESET_PASSWORD' WHERE `accessmenu`.`ID`=24;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_DIRECTORY' WHERE `accessmenu`.`ID`=25;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_DIRECTORY_USERS' WHERE `accessmenu`.`ID`=26;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_DIRECTORY_MATERIALS' WHERE `accessmenu`.`ID`=27;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_DIRECTORY_STAMPS' WHERE `accessmenu`.`ID`=28;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_DIRECTORY_PARAMETRS' WHERE `accessmenu`.`ID`=29;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_DIRECTORY_DESIGNS' WHERE `accessmenu`.`ID`=30;
UPDATE `accessmenu` SET `accessmenu`.`accessValue`='ACCESS_PAGE_DIRECTORY_UNITS' WHERE `accessmenu`.`ID`=31;